### ISSUE TITLE
'BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable' threw an exception of type 'System.InvalidOperationException'

### ISSUE THREAD

**Issue by Arthurvdv** [StefanMaron/BusinessCentral.LinterCop#283]
In our pipeline in Azure DevOps I'm receiving this error

```
warning AD0001: Analyzer 'BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable' threw an exception of type 'System.InvalidOperationException' with message 'System.InvalidOperationException: Nullable object must have a value.
```

AL version: 12.0.779795
LinterCop version: v0.29.1

The problem is I'm not getting this error in VS Code, only when running the pipeline (with the compile ALOpsAppCompiler@2 from ALOps).

Can we easily create a catch for this you do you have a other idea to solve this?

```
Microsoft (R) AL Compiler version 12.0.11.58921
Copyright (C) Microsoft Corporation. All rights reserved
Compilation started for project '<redacted>' containing '70' files at '09:12:08.447'.
warning AD0001: Analyzer 'BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable' threw an exception of type 'System.InvalidOperationException' with message 'System.InvalidOperationException: Nullable object must have a value.
at System.Nullable`1.get_Value()
at BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable.AnalyzeFlowFieldEditable(SymbolAnalysisContext ctx)
at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass49_2.<ExecuteSymbolActionsCore>b__0() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 658
at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1086'
warning AD0001: Analyzer 'BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable' threw an exception of type 'System.InvalidOperationException' with message 'System.InvalidOperationException: Nullable object must have a value.
at System.Nullable`1.get_Value()
at BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable.AnalyzeFlowFieldEditable(SymbolAnalysisContext ctx)
at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass49_2.<ExecuteSymbolActionsCore>b__0() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 658
at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1086'
warning AD0001: Analyzer 'BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable' threw an exception of type 'System.InvalidOperationException' with message 'System.InvalidOperationException: Nullable object must have a value.
at System.Nullable`1.get_Value()
at BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable.AnalyzeFlowFieldEditable(SymbolAnalysisContext ctx)
at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass49_2.<ExecuteSymbolActionsCore>b__0() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 658
at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1086'
C:\azure-vsts-agent-build\_work\559\s\App\Src\Assembly\AssemblyHeader.TableExt.al(66,22): info AA0232: The FlowField Quantity of "Item Ledger Entry" should be added to the SIFT key.
Compilation ended at '09:12:14.070'.
*** AL Compiler raw logs: End
```

**Comment by StefanMaron** [comment]
The problem is, that you are running the al language v12 which is next major. While the linter is compiled against version 11. this might be a bug in the code that pulls the latest vsix version from the marketplace

/Stefan
________________________________
Von: Arthur ***@***.***>
Gesendet: Wednesday, April 5, 2023 9:26:16 AM
An: StefanMaron/BusinessCentral.LinterCop ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [StefanMaron/BusinessCentral.LinterCop] 'BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable' threw an exception of type 'System.InvalidOperationException' (Issue #283)


In our pipeline in Azure DevOps I'm receiving this error

warning AD0001: Analyzer 'BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable' threw an exception of type 'System.InvalidOperationException' with message 'System.InvalidOperationException: Nullable object must have a value.


AL version: 12.0.779795
LinterCop version: v0.29.1

The problem is I'm not getting this error in VS Code, only when running the pipeline (with the compile ***@***.*** from ALOps).

Can we easily create a catch for this you do you have a other idea to solve this?

Microsoft (R) AL Compiler version 12.0.11.58921
Copyright (C) Microsoft Corporation. All rights reserved
Compilation started for project '<redacted>' containing '70' files at '09:12:08.447'.
warning AD0001: Analyzer 'BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable' threw an exception of type 'System.InvalidOperationException' with message 'System.InvalidOperationException: Nullable object must have a value.
at System.Nullable`1.get_Value()
at BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable.AnalyzeFlowFieldEditable(SymbolAnalysisContext ctx)
at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass49_2.<ExecuteSymbolActionsCore>b__0() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 658
at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1086'
warning AD0001: Analyzer 'BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable' threw an exception of type 'System.InvalidOperationException' with message 'System.InvalidOperationException: Nullable object must have a value.
at System.Nullable`1.get_Value()
at BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable.AnalyzeFlowFieldEditable(SymbolAnalysisContext ctx)
at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass49_2.<ExecuteSymbolActionsCore>b__0() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 658
at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1086'
warning AD0001: Analyzer 'BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable' threw an exception of type 'System.InvalidOperationException' with message 'System.InvalidOperationException: Nullable object must have a value.
at System.Nullable`1.get_Value()
at BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable.AnalyzeFlowFieldEditable(SymbolAnalysisContext ctx)
at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass49_2.<ExecuteSymbolActionsCore>b__0() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 658
at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1086'
C:\azure-vsts-agent-build\_work\559\s\App\Src\Assembly\AssemblyHeader.TableExt.al(66,22): info AA0232: The FlowField Quantity of "Item Ledger Entry" should be added to the SIFT key.
Compilation ended at '09:12:14.070'.
*** AL Compiler raw logs: End

**Comment by Arthurvdv** [comment]
@StefanMaron oops! I've should have seen the difference between v11 and v12, a little embarrassing. In my defense I just returned from a small break and was caught in the urgency of this. I've found the issue and created a issue with ALOps to review this.
