### ISSUE TITLE
AL Language Extension 12.x Preview - System.InvalidOperationException Rule0001FlowFieldsShouldNotBeEditable

### ISSUE THREAD

**Issue by pri-kise** [StefanMaron/BusinessCentral.LinterCop#298]
I temporarly switched to the preview and
I receive the following error:
`warning`` AD0001: Analyzer 'BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable' threw an exception of type 'System.InvalidOperationException' with message 'System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable.AnalyzeFlowFieldEditable(SymbolAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass49_2.<ExecuteSymbolActionsCore>b__0() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 658
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1102'
warning AD0001: Analyzer 'Microsoft.Dynamics.Nav.AppSourceCop.Upgrade.RuleInvalidObsoleteTagsNotAllowed' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceFieldSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.FieldGroupSymbol'.
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceTableExtensionTypeSymbol.GetAddedFieldGroups() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceTableExtensionTypeSymbol.cs:line 180
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.TableExtensionTypeSymbol.Microsoft.Dynamics.Nav.CodeAnalysis.ITableExtensionTypeSymbol.get_AddedFieldGroups() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\TableExtensionTypeSymbol.cs:line 58
   at Microsoft.Dynamics.Nav.AppSourceCop.Upgrade.RuleInvalidObsoleteTagsNotAllowed.AnalyzeTableExtension(SymbolAnalysisContext ctx) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.AppSourceCop\Upgrade\RuleInvalidObsoleteTagsNotAllowed.cs:line 152
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass49_2.<ExecuteSymbolActionsCore>b__0() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 658
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1102'

**Comment by Arthurvdv** [comment]
I'm quite certain this is resolved in the meantime, if that's not the cease please reopen this issue.
