### ISSUE TITLE
Error message in rule 40

### ISSUE THREAD

**Issue by Axarath** [StefanMaron/BusinessCentral.LinterCop#438]
Analyzer 'BusinessCentral.LinterCop.Design.Rule0040ExplicitlySetRunTrigger' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundObjectAccess' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IFieldAccess'.
   at Microsoft.Dynamics.Nav.CodeAnalysis.OperationExtensions.GetSymbol(IOperation operation) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\OperationExtensions.cs:line 37
   at BusinessCentral.LinterCop.Design.Rule0040ExplicitlySetRunTrigger.AnalyzeRunTriggerParameters(OperationAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass53_1.<ExecuteOperationAction>b__1() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 766
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1102'

I have this error message only in one extension. I'm not sure what exactly does it mean.

**Comment by Arthurvdv** [comment]
I have no idea what could cause this error, a repo with a small code sample could be of great help.

If I have to take a guess; One of the build-in methods below, is performed on a variable which is not of type Record of RecordRef?

* Insert
* Modify
* ModifyAll
* Delete
* DeleteAll

**Comment by Arthurvdv** [comment]
I've maybe have found a way to mitigate this error message.

Can you try the prelease [v0.30.10](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.10) version of the LinterCop and see if this makes any difference?

**Comment by Axarath** [comment]
Yes, it helpded. Error message disappeared.

**Comment by Arthurvdv** [comment]
Awesome, thanks for verifying this!
