### ISSUE TITLE
BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields causes exceptions

### ISSUE THREAD

**Issue by dsaveyn** [StefanMaron/BusinessCentral.LinterCop#448]
The compilation of one of our apps currently fails cause of an issue with the lintercop. Looking at the error it has to do with a Rule 44 related to transferfields: "**BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields**".

Can this be investigated?

I was not able to pinpoint  the exact line of code that throws this error. 

**Error Details:**

`Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.EmptyPropertySyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.PropertySyntax'.
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.Table.FieldIsObsolete(FieldSyntax field)
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.Table.PopulateFields(FieldListSyntax fieldList)
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.GetTableWithFieldsByTableName(Compilation compilation, String tableName, Dictionary`2 tableExtensions)
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.AnalyzeTransferFields(OperationAnalysisContext ctx)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
`
and
`Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.EmptyPropertySyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.PropertySyntax'.
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.Table.FieldIsObsolete(FieldSyntax field)
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.Table.PopulateFields(FieldListSyntax fieldList)
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.GetTableWithFieldsByTableName(Compilation compilation, String tableName, Dictionary`2 tableExtensions)
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.AnalyzeTransferFields(OperationAnalysisContext ctx)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()`

**Comment by Arthurvdv** [comment]
I think maybe I've found a solution for this error.

Could you try the updated prelease [v0.30.10](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.10) version of the LinterCop and see if this makes any difference?

**Comment by jwikman** [comment]
@Arthurvdv I get another error for LC0044 today, with latest preview:

```
Unhandled exception. Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.<>c.<AnalyzeTransferFields>b__6_0(IArgument args)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.AnalyzeTransferFields(OperationAnalysisContext ctx)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
System.NullReferenceException: Object reference not set to an instance of an object.
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.<>c.<AnalyzeTransferFields>b__6_0(IArgument args)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.AnalyzeTransferFields(OperationAnalysisContext ctx)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

**Comment by Arthurvdv** [comment]
My bad, this was introduced by resolving issue https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/454.

I've moved the SkipFieldsNotMatchingType validation, where this error now should be resolved in the updated (pre)release version [v0.30.10](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.10) of the LinterCop.
