### ISSUE TITLE
LC0044 : Unhandled Exception

### ISSUE THREAD

**Issue by jamesmayr** [StefanMaron/BusinessCentral.LinterCop#565]
Used Version: 0.30.14
I get an exception when I want validate the following Source Code with the Business Central Linter:

```
Subtype = Upgrade;
    Access = Internal;

    trigger OnUpgradePerCompany()
    begin
        MigrateSetup();
        MigrateMapsMarkers();
    end;

    local procedure MigrateSetup()
    var
        _TargetMapsSetupMPIDAG: Record MapsSetupMPIDAG;
        _SourceMapsSetup11IDAG: Record MapsSetup11IDAG;
    begin
        if (_SourceMapsSetup11IDAG.FindSet()) then
            repeat
                if (not _TargetMapsSetupMPIDAG.Get(_SourceMapsSetup11IDAG.PrimaryKey)) then begin
                    _TargetMapsSetupMPIDAG.Init();
                    _TargetMapsSetupMPIDAG.SystemId := _SourceMapsSetup11IDAG.SystemId;
                    _TargetMapsSetupMPIDAG.Insert(false, true);
                end;
                _TargetMapsSetupMPIDAG.TransferFields(_SourceMapsSetup11IDAG, false);
                _TargetMapsSetupMPIDAG.Modify(false);
            until _SourceMapsSetup11IDAG.Next() = 0;
    end;
```
I don't know if its important, but MapsSetupMPIDAG and MapsSetup11IDAG are Tables from Extension that are not part of the workspace.

**Exception:**
Unhandled exception. Unhandled exception. System.ArgumentException: Reported diagnostic 'LC0044' has a source location in file 'xxxxx/MapsSetup.Table.al', which is not part of the compilation being analyzed. (Parameter 'location')
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.DiagnosticAnalysisContextHelpers.VerifyDiagnosticLocationInCompilation(String id, Location location, Compilation compilation) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\DiagnosticAnalysisContextHelpers.cs:line 98
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.DiagnosticAnalysisContextHelpers.VerifyDiagnosticLocationsInCompilation(Diagnostic diagnostic, Compilation compilation) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\DiagnosticAnalysisContextHelpers.cs:line 81
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.DiagnosticAnalysisContextHelpers.VerifyArguments(Diagnostic diagnostic, Compilation compilationOpt, Func`2 isSupportedDiagnostic) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\DiagnosticAnalysisContextHelpers.cs:line 65
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.OperationAnalysisContext.ReportDiagnostic(Diagnostic diagnostic) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalysisContext.cs:line 985
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.ReportFieldDiagnostics(OperationAnalysisContext ctx, Table table, List`1 fieldGroups)
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.AnalyzeTransferFields(OperationAnalysisContext ctx)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

When LC0044  is supressed, everything works fine.

**Comment by Arthurvdv** [comment]
Hi, over the past months I’ve been putting a lot of time and care into the successor of BusinessCentral.LinterCop: ALCops (https://alcops.dev/). Because of that, this repository is no longer actively maintained.

I’m closing this issue, as it won’t be handled here anymore. If this is still relevant for you, please have a look at ALCops/Analyzers (https://github.com/ALCops/Analyzers).

To make the transition easier, you can also follow the LinterCop Migration Guide: https://alcops.dev/docs/lintercop-migration/

If you have any questions or run into issues during the transition, feel free to reach out through ALCops. Happy to help 🙂
