### ISSUE TITLE
Not compatible with AL 13.0?

### ISSUE THREAD

**Issue by NKarolak** [StefanMaron/BusinessCentral.LinterCop#568]
I've just updated the AL Langauge to version 13.0, and I've releaded VS code already twice.

In the PROBLEMs tab, the following warnings are shown for the app.json file:

1)
```
Analyzer 'BusinessCentral.LinterCop.Design.Rule0052InternalProceduresNotReferencedAnalyzer' threw an exception of type 'System.MissingMethodException' with message 'System.MissingMethodException: Method not found: 'Microsoft.Dynamics.Nav.CodeAnalysis.Packaging.NavAppManifest Microsoft.Dynamics.Nav.Analyzers.Common.AppSourceCopConfiguration.AppSourceCopConfigurationProvider.GetManifest(Microsoft.Dynamics.Nav.CodeAnalysis.Compilation)'.
   at BusinessCentral.LinterCop.Design.Rule0052InternalProceduresNotReferencedAnalyzer.MethodSymbolAnalyzer..ctor(CompilationAnalysisContext compilationAnalysisContext)
   at BusinessCentral.LinterCop.Design.Rule0052InternalProceduresNotReferencedAnalyzer.CheckApplicationObjects(CompilationAnalysisContext compilationAnalysisContext)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass49_1.<ExecuteCompilationActionsCore>b__0() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 625
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1088'
```

2)
```
Analyzer 'BusinessCentral.LinterCop.Design.Rule0033AppManifestRuntimeBehind' threw an exception of type 'System.MissingMethodException' with message 'System.MissingMethodException: Method not found: 'Microsoft.Dynamics.Nav.CodeAnalysis.Packaging.NavAppManifest Microsoft.Dynamics.Nav.Analyzers.Common.AppSourceCopConfiguration.AppSourceCopConfigurationProvider.GetManifest(Microsoft.Dynamics.Nav.CodeAnalysis.Compilation)'.
   at BusinessCentral.LinterCop.Design.Rule0033AppManifestRuntimeBehind.CheckAppManifestRuntime(CompilationAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass49_1.<ExecuteCompilationActionsCore>b__0() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 625
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1088'

**Comment by jwikman** [comment]
The last part of your issue (never ending "Loading Workspace") seems to be the same as #567.

Our pipelines that are using LinterCop started to fail yesterday. And it seems to be caused by a change in the BC23.5 container, where the AL Language Extension now is updated to 13.0.14.47012...

Oh, now I see that v13 is already released on VSCode as well!

@Arthurvdv, would this be resolved if you just run your build pipeline? Or are there code changes that needs to be addressed first?

**Comment by NKarolak** [comment]
> Oh, now I see that v13 is already released on VSCode as well!

That's what I meant with "I've just updated the AL Langauge to version 13.0" ;-)
However, check https://github.com/microsoft/AL/issues/7664#issuecomment-2006268582

**Comment by rvanbekkum** [comment]
It seems like `AppSourceCopConfigurationProvider.GetManifest` has been moved to `ManifestHelper.GetManifest` which is the main breaking change for LinterCop.

**Comment by rvanbekkum** [comment]
It looks like the source code did already account for that upcoming change, but now it is a reality. I don't get why Microsoft did this breaking change with an update to v13.x though..

**Comment by Arthurvdv** [comment]
I didn't expect the release of the new v13 version of the AL Language today 😯

There's a breaking change between v12 and v13 in the AL Language, where I already had taken into account in the prerelease and now switched to the release version of the LinterCop.

If you updatye to the latest release version of the LinterCop [v0.30.15](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.15) those error should be gone.

**Comment by NKarolak** [comment]
> If you updatye to the latest release version of the LinterCop [v0.30.15](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.15) those error should be gone.

How do I do that? I am just using the BusinessCentral.LinterCop extension, v0.1.6

**Comment by Arthurvdv** [comment]
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/44637996/2534843d-af84-4ae2-92a1-ee7c021bae5f)

There's an action for that. Best pratice is to not have an AL project open/active (this will lock the .dll file). Closing all VS Code windows should also work (on opening VS Code it will also automatically update to the latest version of the LinterCop).

**Comment by NKarolak** [comment]
> I didn't expect the release of the new v13 version of the AL Language today 😯

Nobody did - even not Microsoft 😁
https://x.com/SBalslev/status/1770020492910485759?s=20

> There's an action for that. 

Thank you! Despite a missing notification (hitting the action returned nothing to the UI) it is now working again.
