### ISSUE TITLE
Rule0044AnalyzeTransferFields - Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.PageExtensionSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.TableExtensionSyntax'.

### ISSUE THREAD

**Issue by pri-kise** [StefanMaron/BusinessCentral.LinterCop#589]
We receive the following warning in our Azure DevOps pipeline.

```
##[warning]warning AD0001: Analyzer 'BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.PageExtensionSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.TableExtensionSyntax'.
##[warning]at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.AnalyzeTableExtension(SyntaxNodeAnalysisContext ctx)
##[warning]at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass52_1.<ExecuteSyntaxNodeAction>b__1() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 745
##[warning]at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1086'
##[warning]warning AD0001: Analyzer 'BusinessCentral.LinterCop.Design.Rule0033AppManifestRuntimeBehind' threw an exception of type 'System.MissingMethodException' with message 'System.MissingMethodException: Method not found: 'Microsoft.Dynamics.Nav.CodeAnalysis.Packaging.NavAppManifest Microsoft.Dynamics.Nav.Analyzers.Common.ManifestHelper.GetManifest(Microsoft.Dynamics.Nav.CodeAnalysis.Compilation)'.

```

We only have on PageExtension in this app, because this is our template app.
```al
pageextension 50000 "PTE CustomerListExt" extends "Customer List"
{
    trigger OnOpenPage();
    begin
        //Message('App published: Hello world');
    end;
}
```

Versions:
- Microsoft (R) AL Compiler version 12.7.14.63589
- Application Version: 23.5

Might be related to #588

**Comment by Arthurvdv** [comment]
Related to https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/590

**Comment by pri-kise** [comment]
I've tested it with the Latest AL Language version.
Now it's working fine.
I will have to update our pipelines now, but at least it's working now.
