### ISSUE TITLE
LC0039 Rule0039ArgumentDifferentTypeThenExpected

### ISSUE THREAD

**Issue by SKeiler** [StefanMaron/BusinessCentral.LinterCop#635]
Hi,

we try to implement the rules on our ISV. So I'm not sure if it's a "local" problem in our environment or a problem with the project. We use it currently for BC23.4. We installed the LinterCop-VSC Extension and get the following warning in our project. 

Analyzer 'BusinessCentral.LinterCop.Design.Rule0039ArgumentDifferentTypeThenExpected' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SimpleNavTypeSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IRecordTypeSymbol'.
   at BusinessCentral.LinterCop.Design.Rule0039ArgumentDifferentTypeThenExpected.AnalyzeSetRecordArgument(OperationAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass54_1.<ExecuteOperationAction>b__1() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 773
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1088'

We are a little bit unsure what's the reason of the warning. Can you please give us a hint as to what the cause is.

**Comment by Arthurvdv** [comment]
Thank you for creating an issue, there's probably something wrong.

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/44637996/058aae02-c135-4785-ae9c-3a1496a9a981)

Could you switch over to the pre-release version of the LinterCop and try again? After reloading VS Code you should find a LC0000 diagnostic pointing to the line of code causing this error. Would be great if you could share a small portion of the code (or recreate a small sample 0>

**Comment by SKeiler** [comment]
Hi,

seem's to be a SetTableView based on a Variant-Record.
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/45033081/7e2c8dba-3dcb-433d-a7a9-38652b9cce1e)

**Comment by Arthurvdv** [comment]
This should now be resolved in the release version of [v0.30.25](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.25) of the LinterCop.
