### ISSUE TITLE
InvalidCastException: 'Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceChangeAddActionSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IActionSymbol'.'

### ISSUE THREAD

**Issue by Arthurvdv** [StefanMaron/BusinessCentral.LinterCop#645]
Found an issue related with https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/587, where the code below throws and exception.

```AL
pageextension 50010 "Delivery Specifications" extends "Delivery Specifications"
{
    actions
    {
        addlast(Promoted)
        {
            group(Labels)
            {
                ShowAs = SplitButton;
            }
        }
    }
}
```

```Exception has occurred: CLR/System.InvalidCastException
An exception of type 'System.InvalidCastException' occurred in BusinessCentral.LinterCop.dll but was not handled in user code: 'Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceChangeAddActionSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IActionSymbol'.'
   at BusinessCentral.LinterCop.Design.Rule0016CheckForMissingCaptions.CheckForMissingCaptions(SymbolAnalysisContext context) in C:\Users\arthur.vandevondervo\repo\BusinessCentral.LinterCop\Design\Rule0016CheckForMissingCaptions.cs:line 98
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass50_2.<ExecuteSymbolActionsCore>b__0()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)```

**Comment by Arthurvdv** [comment]
This should now be resolved in the release version of [v0.30.25](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.25) of the LinterCop.
