### ISSUE TITLE
LC0054 'BusinessCentral.LinterCop.Design.Rule0054FollowInterfaceObjectNameGuide' threw an exception of type 'System.NullReferenceException'

### ISSUE THREAD

**Issue by pri-kise** [StefanMaron/BusinessCentral.LinterCop#671]
Since today I receive the following error.
```
Analyzer 'BusinessCentral.LinterCop.Design.Rule0054FollowInterfaceObjectNameGuide' threw an exception of type 'System.NullReferenceException' with message 'System.NullReferenceException: Object reference not set to an instance of an object.
   at BusinessCentral.LinterCop.Design.Rule0054FollowInterfaceObjectNameGuide.GetIndexAfterAffix(String typeSymbolName)
   at BusinessCentral.LinterCop.Design.Rule0054FollowInterfaceObjectNameGuide.AnalyzeObjectName(SymbolAnalysisContext context)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass50_2.<ExecuteSymbolActionsCore>b__0() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 665
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1088'
```

AL Language Extension: v14.0.1055126

**Comment by tscottjendev** [comment]
Me too.

**Comment by Arthurvdv** [comment]
I think I've found the reason for this Exception (I didn't test without an AppSourceCop.json file exists in the project).

@pri-kise and @tscottjendev , did this resolve the Exception?

**Comment by pri-kise** [comment]
I checked this project again and we have an AppSourceCop.json, but in this project we haven't specified the property `mandatoryAffixes`, but the property `mandatoryPrefix`.

Maybe this is the reason for the issue?
