### ISSUE TITLE
Rule0044AnalyzeTransferFields - unhandled cast exception from OptionValuesSyntax to GlobalVarSectionSyntax

### ISSUE THREAD

**Issue by a-gnius** [StefanMaron/BusinessCentral.LinterCop#774]
We receive the following error:
```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.OptionValuesSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.GlobalVarSectionSyntax'.
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.FindGlobalVariables(SyntaxNode node)
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.AnalyzeTransferFields(OperationAnalysisContext ctx)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
As I understand it is something with TransferFields and Option values. Any idea what we should look for?

**Comment by Arthurvdv** [comment]
I've did some improvements and error handling on this rule with a [few weeks ago.](https://github.com/StefanMaron/BusinessCentral.LinterCop/pull/799) and with the release of [v0.31.2](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.31.2) of the LinterCop I'm hoping this has now resolved this issue.

Could you check again and let me know if this issue now has been resolved?
