### ISSUE TITLE
Rule0024SemicolonAfterMethodOrTriggerDeclaration - System.NullReferenceException

### ISSUE THREAD

**Issue by a-gnius** [StefanMaron/BusinessCentral.LinterCop#775]
Do you have any thoughts on what is causing the issue?
```
Analyzer 'BusinessCentral.LinterCop.Design.Rule0024SemicolonAfterMethodOrTriggerDeclaration' threw an exception of type 'System.NullReferenceException' with message 'System.NullReferenceException: Object reference not set to an instance of an object.
   at BusinessCentral.LinterCop.Design.Rule0024SemicolonAfterMethodOrTriggerDeclaration.AnalyzeSemicolonAfterMethodOrTriggerDeclaration(SyntaxNodeAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass53_1.<ExecuteSyntaxNodeAction>b__1() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 752
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable'1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1095'
```

**Comment by Arthurvdv** [comment]
I've added additional error handling to this rule in the (pre-release) version [v0.31.2](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.31.2) of LinterCop.  
Could you switch to the pre-release version of the LinterCop and verify if it resolves the issue?

**Comment by Arthurvdv** [comment]
@a-gnius I wanted to follow up on this issue to check if you are still encountering this exception.

If the issue is no longer relevant or has been resolved, please let me know, and we can close this issue.

**Comment by a-gnius** [comment]
With the v0.31.2 I don't encounter this exception anymore. Thanks
