### ISSUE TITLE
LC0044 - threw an exception of type 'System.InvalidCastException'

### ISSUE THREAD

**Issue by NAVFreak** [StefanMaron/BusinessCentral.LinterCop#786]
Hi,

This morning I got the following exception in my pipelines below. 
We are not  not running prerelease and this is the "lastversion" we get: 2024-10-02T13:20:25Z

We currently can't use the code analyzer at all for this project 😫

```
##[warning]warning AD000***: Analyzer 'BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.ReportExtensionSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.TableExtensionSyntax'.
##[warning]at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.AnalyzeTableExtension(SyntaxNodeAnalysisContext ctx)
##[warning]at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass53_***.<ExecuteSyntaxNodeAction>b__***() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 75***
##[warning]at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`*** info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line ***095'
##[warning]warning AD000***: Analyzer 'BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.ReportExtensionSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.TableExtensionSyntax'.
##[warning]at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.AnalyzeTableExtension(SyntaxNodeAnalysisContext ctx)
##[warning]at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass53_***.<ExecuteSyntaxNodeAction>b__***() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 75***
##
```

**Comment by NAVFreak** [comment]
It didn't help with removing the rule LC0044 in the ruleset

        {
            "id": "LC0044",
            "action": "None",
            "justification": "transferfields, currently bug in analyzer"
        },

**Comment by Arthurvdv** [comment]
I've added an try/catch which now should raise the LC0000 diagnostic in the pre-release [v0.31.2](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.31.2) version of the LinterCop.

Would be great if you could share a code snippet that causes this error.

**Comment by NAVFreak** [comment]
Now it compiles with version 2024-10-13T14:19 pre-release, but it seems LC0002 stopped working in that version.

Here is the diagnostics.
```
2024-10-15T06:15:48.8642457Z Char         : ***
2024-10-15T06:15:48.8643093Z AlertMessage : There was an Error in Rule "Rule0044" of type "Exception" at line ***6
2024-10-15T06:15:48.8645156Z AlertLevel   : info
2024-10-15T06:15:48.8645915Z RelativePath : \vsts-agent-win-x64-***.***3.***\_work\***83\s\App\Src\FooMakeShipment\NBAFooMakeShipment.ReportExt.al
2024-10-15T06:15:48.8647879Z Line         : ***
2024-10-15T06:15:48.8648243Z AlertCode    : LC0000
2024-10-15T06:15:48.8649731Z File         : NBAFooMakeShipment.ReportExt.al
```

Code for object that gets this error
```
reportextension 50001 "NBA Foo Make Shipment" extends "Foo Make Shipment"
{
    requestpage
    {
        layout
        {
            addafter(ShipToDateFld)
            {
                field(ShipToTimeFld; ShipToTime)
                {
                    ApplicationArea = All;
                    Caption = 'Ship To Time';
                    ToolTip = 'Specifies the value of the Ship To Time field.';
                    trigger OnValidate()
                    var
                        FooRentalSetup: Record "Foo Rental Setup";
                        NBAMakeShptSingleInstance: Codeunit "NBA Make Shpt Single Instance";
                        lShipToDate: Date;
                    begin
                        FooRentalSetup.Get();
                        lShipToDate := NBAMakeShptSingleInstance.GetShipDate();
                        if ShipToTime > FooRentalSetup."NBA Time for new On-rent day" then
                            SetOnRentDate(CalcDate('<+1D>', lShipToDate))
                        else
                            SetOnRentDate(lShipToDate);
                    end;
                }
            }
        }
        procedure SetShipToTime(NewShipToTime: Time)
        begin
            ShipToTime := NewShipToTime;
        end;

        var
            FooMakeReturn: Report "Foo Make Return";
            ShipToTime: Time;

    }

}
```

**Comment by Arthurvdv** [comment]
Unfortunately, I couldn’t reproduce the exception, but I do believe I’ve found a solution for this.

Could you very this with the pre-release [v0.31.2](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.31.2) version of the LinterCop?

**Comment by NAVFreak** [comment]
Hi,

Can't see which version I'm currently using since I get scrambled URL in my feed. It would have been nice if you add the version no. to the lastversion file

Downloading PowerShell script  from https://raw.githubusercontent.com/StefanMaron/vsc-lintercop/master/DownloadFile.ps***...
Success. Now executing DownloadFile.ps***
Artifact found: BusinessCentral.LinterCop.dll
Retrieving artifact 
```
https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/download/v0.3***.***/BusinessCentral.LinterCop.dll
0

Content of lastversion.txt:
***0***4-***-0***T***6:***7:5***Z

Content of lastversion.txt (letters):
TwoZeroTwoFour-OneOne-ZeroOneTOneSix:TwoSeven:FiveOneZ
```

Anyhow, seems to work without any problem.

**Comment by Arthurvdv** [comment]
Great to hear it's seems to work without any problem now. I'm going to close this issue here, feel free to reopen if the problem reoccurs.
