### ISSUE TITLE
AL Language v15.0.1251530 (pre-release) crashing - Rule 0044 System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundConversion' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IInvocationExpression'.

### ISSUE THREAD

**Issue by pri-kise** [StefanMaron/BusinessCentral.LinterCop#828]
Since today I got the following error in my output.
```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundConversion' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IInvocationExpression'.
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.AnalyzeTransferFields(OperationAnalysisContext ctx)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by LeneKrogholm** [comment]
I have the same issue. I found out it does not crash if I remove a line using CopyStr.
I have tried re-writing it in different ways but it crashes every time.

**Comment by Arthurvdv** [comment]
I've added an try/catch to the rule on this method in the Pre-Release [v0.31.3](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.31.3). Could you try this version and look for a LC0000 diagnostic?

Would be great if you could share a small code sample here to reproduce this error.

**Comment by pri-kise** [comment]
here is one place:
```al
ReservationEntry.SetRange("Source Subtype", SalesLine."Document Type".AsInteger()); //There was an Error in Rule "Rule0044" of type "InvalidCastException" 
```

And here is another LC0000:
```al
ReservationEntry.SetRange("Reservation Status", ReservationEntry."Reservation Status"::Surplus); //There was an Error in Rule "Rule0017" of type "InvalidCastException" at Line 41
ReservationEntry.SetRange("Source Ref. No.", SalesLine."Line No."); //There was an Error in Rule "Rule0017" of type "InvalidCastException" at Line 41
```

From an API Page:
```al
                field(jobTitle; Rec."Job Title")
                {
                    Caption = 'Job Title';
                    ShowMandatory = true;

                    trigger OnValidate()
                    begin
                        RegisterFieldSet(Rec.FieldNo("Job Title")); // There was an Error in Rule "Rule0017" of type "InvalidCastException" at Line 41
                    end;
                }
```

In this app I have now several warnings in the app.json for an invalid cast:
```
Analyzer 'BusinessCentral.LinterCop.Design.Rule0039ArgumentDifferentTypeThenExpected' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundConversion' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IInvocationExpression'.
   at BusinessCentral.LinterCop.Design.Rule0039ArgumentDifferentTypeThenExpected.AnalyzeRunPageArguments(OperationAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass54_1.<ExecuteOperationAction>b__1() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 773
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1088'
```

````
Analyzer 'BusinessCentral.LinterCop.Design.Rule0028CodeNavigabilityOnEventSubscribers' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.TriggerDeclarationSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.MethodDeclarationSyntax'.
   at BusinessCentral.LinterCop.Design.Rule0028CodeNavigabilityOnEventSubscribers.AnalyzeIdentifiersInEventSubscribers(CodeBlockAnalysisContext context)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass56_2`2.<ExecuteBlockActions>b__1() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 929
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1088'
```

```
Analyzer 'BusinessCentral.LinterCop.Design.Rule0027RunPageImplementPageManagement' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundConversion' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IInvocationExpression'.
   at BusinessCentral.LinterCop.Design.Rule0027RunPageImplementPageManagement.CheckRunPageImplementPageManagement(OperationAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass54_1.<ExecuteOperationAction>b__1() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 773
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1088'
```

```
Analyzer 'BusinessCentral.LinterCop.Design.Rule0032ClearCodeunitSingleInstance' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundConversion' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IInvocationExpression'.
   at BusinessCentral.LinterCop.Design.Rule0032ClearCodeunitSingleInstance.ClearAllCodeunit(OperationAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass54_1.<ExecuteOperationAction>b__1() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 773
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1088'
```

```
Analyzer 'BusinessCentral.LinterCop.Design.Rule0048ErrorWithTextConstant' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundConversion' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IInvocationExpression'.
   at BusinessCentral.LinterCop.Design.Rule0048ErrorWithTextConstant.AnalyzeErrorMethod(OperationAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass54_1.<ExecuteOperationAction>b__1() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 773
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1088'
```

```
Analyzer 'BusinessCentral.LinterCop.Design.Rule0050OperatorAndPlaceholderInFilterExpression' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundConversion' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IInvocationExpression'.
   at BusinessCentral.LinterCop.Design.Rule0050OperatorAndPlaceholderInFilterExpression.AnalyzeInvocation(OperationAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass54_1.<ExecuteOperationAction>b__1() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 773
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1088'
```

```
Analyzer 'BusinessCentral.LinterCop.Design.Rule0040ExplicitlySetRunTrigger' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundConversion' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IInvocationExpression'.
   at BusinessCentral.LinterCop.Design.Rule0040ExplicitlySetRunTrigger.AnalyzeRunTriggerParameters(OperationAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass54_1.<ExecuteOperationAction>b__1() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 773
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1088'
```

```
Analyzer 'BusinessCentral.LinterCop.Design.BuiltInMethodImplementThroughCodeunit' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundConversion' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IInvocationExpression'.
   at BusinessCentral.LinterCop.Design.BuiltInMethodImplementThroughCodeunit.AnalyzeConfirm(OperationAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass54_1.<ExecuteOperationAction>b__1() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 773
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1088'
```


```
Analyzer 'BusinessCentral.LinterCop.Design.Rule0043SecretText' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundConversion' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IInvocationExpression'.
   at BusinessCentral.LinterCop.Design.Rule0043SecretText.AnalyzeHttpObjects(OperationAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass54_1.<ExecuteOperationAction>b__1() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 773
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1088'
```

**Comment by LeneKrogholm** [comment]
@Arthurvdv my problem has been solved. Thank you very much

**Comment by Arthurvdv** [comment]
@LeneKrogholm, I was hoping that you VS Code would show you an LC0000 diagnostic. This could be of great help on determine the root cause with a small code sample. Would be great if you could check if can find a LC0000 diagnostic now?

@pri-kise, Could it that the VS Code extension of the LinterCop maybe has downloaded the wrong .dll file?
![image](https://github.com/user-attachments/assets/738373a0-cadb-4a11-ab68-482241267612)

At first I couldn't setup an repo on your error, but with switch back-and-forth in VS Code on the Release and Pre-Release version of the LinterCop I now find myself having the wrong version of the LinterCop.

@StefanMaron I think I have a repo: Start with VS Code on 14.2 (Release) and then switch in the AL Language to the 15.0 (Pre-Releas) and reload the AL Language extension without closing VS Code. After closing en opening VS Code again, I seems that then I have the wrong version of the LinterCop.

**Comment by LeneKrogholm** [comment]
@Arthurvdv sorry I only checked quickly Friday and it turned out LinterCop had not downloaded correctly.
I get all of these:
![image](https://github.com/user-attachments/assets/390bb134-e45c-40b9-9a38-aa5fc0a5d7e5)

E.g. first line references to this line where everything looks ok.
![image](https://github.com/user-attachments/assets/25adc48d-e4ee-4503-a616-675d8e5439a1)

Rule0044-lines are all relating to lines with CopyStr but everything looks ok.

**Comment by Arthurvdv** [comment]
@LeneKrogholm I believe I've resolved the LC0000 diagnostics on the Rule0017 in the Pre-release [v0.31.4](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.31.4) version of the LinterCop.

**Comment by LeneKrogholm** [comment]
@Arthurvdv fantastic. Just downloaded and everything seems to be working beautifully. Thanks.
