### ISSUE TITLE
LC0013 threw an exception of type 'System.InvalidCastException'

### ISSUE THREAD

**Issue by rvanbekkum** [StefanMaron/BusinessCentral.LinterCop#96]
Hi @StefanMaron,

Rule LC0013 raises the following error for us:
```
Analyzer 'BusinessCentral.LinterCop.Design.Rule0013CheckForNotBlankOnSingleFieldPrimaryKeys' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceTableExtensionTypeSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.ITableTypeSymbol'.
   at BusinessCentral.LinterCop.Design.Rule0013CheckForNotBlankOnSingleFieldPrimaryKeys.CheckForSingleFieldPrimaryKeysNotBlank(SymbolAnalysisContext context)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass49_2.<ExecuteSymbolActionsCore>b__0() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 656
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1100'
```
This can be reproduced with an app with a table extension on the Item table, e.g.:
```al
tableextension 50100 ItemExt extends Item
{
    fields
    {
        field(50100; MyField; Code[20])
        {
            Caption = 'MyField';
            DataClassification = CustomerContent;
        }
    }
}

```

**Comment by StefanMaron** [comment]
This should be fixed with the latest version.
